[ru]
  languageName = "Russian"
  contentDir = "content/ru"
  weight = 10
  [ru.params]
    languageISO = "RU"

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 15
  [en.params]
    languageISO = "EN"

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 20
  [de.params]
    languageISO = "DE"

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 25
  [nl.params]
    languageISO = "NL"
    titleAddition = "Ctlos Linux — iso образ, основанный на Arch Linux"
    description = "Созданный с помощью archiso скриптов."
    titleHome = "Ctlos Linux"
    footer = "Gen: <a href=\"https://gohugo.io\">Hugo</a> | Fork: <a href=\"https://getdoks.org\">Doks</a>"
    alertText = "Курс: Администратор Linux <a target=\"_blank\" class=\"alert-link stretched-link\" href=\"https://go.acstat.com/dd8dd6e6d0d585c0\">Подробнее</a>"
