# Meta Data for SEO

## Homepage
title = "Hafzan Holdings"
titleSeparator = "|"
titleAddition = ""
description = ""

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["post.png"]
ogLocale = "en_EN"
domainTLD = "hafzan-technologies.github.io"
titleHome = "Hafzan Holdings"

## Twitter Cards
twitterSite = "@hafzanholdings"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Hafzan Holdings"
schemaAuthor = "Amaanullah Bhatti"
schemaAuthorGitHub = "https://github.com/ammanullah"
schemaLocale = "en-EN"
schemaLogo = "logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "post.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/hafzanholdings"
schemaGitHub = "https://github.com/hafzan-technologies"
schemaSection = "changelog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Created by: <a target=\"_blank\" rel=\"noopener\" href=\"https://github.com/hafzan-technologies\">Hafzan Technologies</a>"

# Feed
copyRight = "Copyright (c) Hafzan Holdings"

# Alert
#alert = false
#alertDismissable = true
#alertText = "Курс: Администратор Linux <a target=\"_blank\" rel=\"noopener\" class=\"alert-link stretched-link\" href=\"https://go.acstat.com/dd8dd6e6d0d585c0\">Подробнее</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab]
repoHost = "GitHub"
docsRepo = "https://github.com/ammanullah/hafzan-technologies.github.io"
docsRepoBranch = "master"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = true
  wikiVersioning = false
